<?php $auth = Zend_Auth::getInstance(); //session initialisé
?>

<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <script src="https://code.jquery.com/jquery-3.7.1.min.js"
        integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.7.1.js"></script>
</head>

<body>
    <h1>HCRUD</h1>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">CRUD</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page"
                            href="<?php echo $this->url(array('controller' => 'produit', 'action' => 'index')); ?>">Accueil</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link"
                            href="<?php echo $this->url(array('controller' => 'produit', 'action' => 'listeproduit')); ?>">Liste
                            des
                            produits</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link"
                            href="<?php echo $this->url(array('controller' => 'produit', 'action' => 'ajout')); ?>">Nouveau
                            produit</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link"
                            href="<?php echo $this->url(array('controller' => 'produit', 'action' => 'stockparproduit')); ?>">Stock
                            actuelle</a>
                    </li>
                    <?php if ($auth->hasIdentity()): ?>
                        <li class="nav-item">
                            <a class="nav-link"
                                href="<?php echo $this->url(array('controller' => 'utilisateur', 'action' => 'logout')); ?>">Deconnexion
                            </a>
                        </li>
                    <?php else : ?>
                        <li class="nav-item">
                            <a class="nav-link"
                                href="<?php echo $this->url(array('controller' => 'utilisateur', 'action' => 'login')); ?>">Connexion
                            </a>
                        </li>
                    <?php endif ?>
                </ul>
            </div>
            <select id="moduleSelect" class="form-select">
                <option value="">----- choix du module ----</option>
                <option value="<?php echo $this->url(['controller' => 'francetravailnew', 'action' => 'index']); ?>">
                    offre d'emploi
                </option>
                <option
                    value="<?php echo $this->url(['controller' => 'francetravailnew', 'action' => 'entrepriserecrutement']); ?>">
                    entreprise recrutement
                </option>
                <option value="<?php echo $this->url(['controller' => 'francetravailnew', 'action' => 'services']); ?>">
                    services
                </option>
                <option
                    value="<?php echo $this->url(['controller' => 'francetravailnew', 'action' => 'marchetravaillocal']); ?>">
                    marché travail local
                </option>
            </select>


        </div>
    </nav>
    <?php echo $this->layout()->content; ?>
    <!-- <script>
        document.getElementById('moduleSelect').addEventListener('change', function() {
            if (this.value) {
                window.location.href = this.value;
            }
        });
    </script> -->

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI" crossorigin="anonymous">
    </script>
</body>

</html>